import unreal, os

# FileFix.py by Cheebsta
# Corrects display names of dummy objects in Content Browser

# This thing is SLLLOOOOOOOWWWWWWWWWWW, like up to an hour slow.
# If you can speed it up please do.

# You will need:
# The Python plugin for UE
# The Editor Scripting Plugin for UE
# A template generated by my other script

loc = "/Game/"
DIR = unreal.EditorAssetLibrary.list_assets(loc, True, True)

# UE names files like FileName.DisplayName
# Content Browser shows DisplayName
# Template Generator names files correctly, but Dummy DisplayName remains
# For some crazy reason scripts are not allowed to change only DisplayName
# So we must create a temp file to swap in
# This is 2 moves and 1 delete, plus, I think, 2 loads, 2 saves, and 2 unloads
# Times 3500 objects (5500 with textures)... Many thousands of CB operations :(

for i in DIR:
  assetPathNow = i
  fileName = os.path.basename(i)
  if "." in fileName:
    sf = fileName.split(".")
    fileName = "/%s.%s" % (sf[0], sf[0])
    fileName2 = "/%sTMP.%sTMP" % (sf[0], sf[0])
    newName = os.path.dirname(i) + fileName
    newName2 = os.path.dirname(i) + fileName2
    unreal.EditorAssetLibrary.rename_asset(assetPathNow, newName2)
    unreal.EditorAssetLibrary.delete_asset(newName)
    unreal.EditorAssetLibrary.rename_asset(newName2, newName)
